version: "3.7"
services:
  pocketbase-filerr:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: filerr-pocketbase
    restart: unless-stopped
    volumes:
      - pb_data:/pb_data
      - pb_public:/pb_public
    ports:
      - "8090:8090"
  filerr-proxy:
    image: filerr-proxy:latest
    build: ./nginx
    container_name: filerr-proxy
    restart: unless-stopped
    ports:
      - "5050:5050"

volumes:
  pb_data:
  pb_public: