name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [master]
    paths-ignore:
      - 'nginx/**'
      - 'server/**'

jobs:
  # define job to build and publish docker image

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Create env file
        run: |
          touch .env
          echo PUBLIC_URL=${PUBLIC_URL} > .env
          echo PUBLIC_APPWRITE_ENDPOINT=${PUBLIC_APPWRITE_ENDPOINT} > .env
          echo PUBLIC_APPWRITE_PROJECT=${PUBLIC_APPWRITE_PROJECT} > .env
          echo PUBLIC_APPWRITE_DATABASE_ID=${PUBLIC_APPWRITE_DATABASE_ID} > .env
          echo PUBLIC_APPWRITE_COLLECTION_ID=${PUBLIC_APPWRITE_COLLECTION_ID} > .env
          echo PUBLIC_APPWRITE_TEAM_ADMIN_ID=${PUBLIC_APPWRITE_TEAM_ADMIN_ID} > .env
          cat .env
        env: 
          PUBLIC_URL: ${{ secrets.FILERR_PUBLIC_URL }}
          PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.PUBLIC_APPWRITE_ENDPOINT }}
          PUBLIC_APPWRITE_PROJECT: ${{ secrets.PUBLIC_APPWRITE_PROJECT }}
          PUBLIC_APPWRITE_DATABASE_ID: ${{ secrets.PUBLIC_APPWRITE_DATABASE_ID}}
          PUBLIC_APPWRITE_COLLECTION_ID: ${{ secrets.PUBLIC_APPWRITE_COLLECTION_ID }}
          PUBLIC_APPWRITE_TEAM_ADMIN_ID: ${{ secrets.PUBLIC_APPWRITE_TEAM_ADMIN_ID }}


  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    needs: create-envfile

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/emilzackrisson/filerr:latest
          # build on feature branches, push only on master branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
